import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
   MatButtonModule,
   MatToolbarModule,
   MatIconModule,
   MatBadgeModule,
   MatSidenavModule,
   MatListModule,
   MatGridListModule,
   MatFormFieldModule,
   MatInputModule,
   MatSelectModule,
   MatRadioModule,
   MatDatepickerModule,
   MatNativeDateModule,
   MatChipsModule,
   MatTooltipModule,
   MatTableModule,
   MatPaginatorModule,
   MatAutocompleteModule,
   MatCheckboxModule,
   MatSliderModule,
   MatSlideToggleModule,
   MatMenuModule,
   MatCardModule,
   MatDividerModule,
   MatExpansionModule,
   MatStepperModule,
   MatTabsModule,
   MatTreeModule,
   MatButtonToggleModule,
   MatProgressSpinnerModule,
   MatProgressBarModule,
   MatRippleModule,
   MatBottomSheetModule,
   MatDialogModule,
   MatSnackBarModule,
   MatSortModule

} from '@angular/material';

@NgModule({
   imports: [
      CommonModule,
      MatButtonModule,
      MatToolbarModule,
      MatSidenavModule,
      MatBadgeModule,
      MatListModule,
      MatGridListModule,
      MatFormFieldModule,
      MatInputModule,
      MatSelectModule,
      MatNativeDateModule,
      MatAutocompleteModule,
      MatCheckboxModule,
      MatDatepickerModule,
      MatRadioModule,
      MatSliderModule,
      MatSlideToggleModule,
      MatMenuModule,
      MatCardModule,
      MatDividerModule,
      MatExpansionModule,
      MatStepperModule,
      MatTabsModule,
      MatTreeModule,
      MatButtonToggleModule,
      MatChipsModule,
      MatIconModule,
      MatProgressSpinnerModule,
      MatProgressBarModule,
      MatRippleModule,
      MatBottomSheetModule,
      MatDialogModule,
      MatSnackBarModule,
      MatTooltipModule,
      MatPaginatorModule,
      MatSortModule,
      MatTableModule
   ],
   exports: [
      CommonModule,
      MatButtonModule,
      MatToolbarModule,
      MatSidenavModule,
      MatBadgeModule,
      MatListModule,
      MatGridListModule,
      MatFormFieldModule,
      MatInputModule,
      MatSelectModule,
      MatNativeDateModule,
      MatAutocompleteModule,
      MatCheckboxModule,
      MatDatepickerModule,
      MatRadioModule,
      MatSliderModule,
      MatSlideToggleModule,
      MatMenuModule,
      MatCardModule,
      MatDividerModule,
      MatExpansionModule,
      MatStepperModule,
      MatTabsModule,
      MatTreeModule,
      MatButtonToggleModule,
      MatChipsModule,
      MatIconModule,
      MatProgressSpinnerModule,
      MatProgressBarModule,
      MatRippleModule,
      MatBottomSheetModule,
      MatDialogModule,
      MatSnackBarModule,
      MatTooltipModule,
      MatPaginatorModule,
      MatSortModule,
      MatTableModule
   ],
   providers: [
      MatDatepickerModule,
   ]
})

export class AngularMaterialModule { }